spring:
  application:
    name: PromoService

  Redis:
    host: spring.data.redis.host=redis
    port: localhost:6379
    version: redis:latest
    password: myStrongPassword

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: promo-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        schema:
          registry:
            url: http://localhost:8081

myapp:
  kafka:
    game-events:
      topic: "game.events"
      concurrency: 3
    tournament-events:
      topic: "tournament.events"
      concurrency: 3
    leaderboard-events:
      topic: "leaderboard.events"
      concurrency: 3
